@CrudOrders.API_HostAddress = http://localhost:5234

### Get all orders
GET {{CrudOrders.API_HostAddress}}/api/orders
Accept: application/json

### Get order by id
GET {{CrudOrders.API_HostAddress}}/api/orders/1
Accept: application/json

### Create order
POST {{CrudOrders.API_HostAddress}}/api/orders
Content-Type: application/json

{
  "nomeCliente": "John Doe",
  "emailCliente": "john@example.com",
  "pago": false,
  "itensPedido": [
    {
      "idProduto": 1,
      "nomeProduto": "Widget",
      "valorUnitario": 9.99,
      "quantidade": 2
    }
  ]
}

### Delete order
DELETE {{CrudOrders.API_HostAddress}}/api/orders/1

###
